---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rollout
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: summer-k8s-app
  template:
    metadata:
      labels:
        app: summer-k8s-app
    spec:
      containers:
      - name: webserver-simple
        image: lrochette/colors:purple
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
