---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rollout
spec:
  revisionHistoryLimit: 1
  replicas: 13
  selector:
    matchLabels:
      app: summer-k8s-app
  template:
    metadata:
      labels:
        app: summer-k8s-app
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/todaywasawesome/colors:v0.0.1-alpha
        imagePullPolicy: Always
        env:
        - name: COLOR
          value: '#44B3C2'
        ports:
        - containerPort: 8080
