---
apiVersion: v1
kind: Service
metadata:
  name: summer-k8s-service-stable
  labels:
    app: summer-k8s-app  
spec:
  type: NodePort
  selector:
    app: summer-k8s-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080     