apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: colors
  name: colors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colors

  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: colors
        
    spec:
      containers:
      - image: containers101/color-coded:master
        imagePullPolicy: Always
        name: colors
        # env:
        # - name: COLOR
        #   value: '#44B3C2'
        ports:
        - containerPort: 8080
          protocol: TCP

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

---
apiVersion: v1
kind: Service
metadata:
  name: colors
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: colors
  sessionAffinity: None
  type: ClusterIP
